### ISSUE TITLE
find, sort, order

### ISSUE THREAD

**Issue by Skandinavchik** [apollographql/spacex#26]
I'm sorry if writing wrong in issue, I'm first time here but can't find out how find, sort and order works.
I tried this query and limit and offset working as expected but not sort and order.

```graphql
query Lauches {
	launchesPast(limit: 10, offset: 0, order: "???") {
		id
		mission_name
	}
}
```

Can somebody please help with this?

**Comment by shelbycotton** [comment]
Were you able to figure this out? I’ve been having trouble implementing this as well.
